### PR TITLE
10.5 compatibility (kinda)

### PR DESCRIPTION
**Pull request by dgilman**
This makes the vitunes-tool-objc build and run under 10.5.  vitunes runs and works but the tool produces an error message 'unknown type name "tdta"'. This extra output clutters up vitunes a bit and creates lots of those little error windows in vim you have to press ENTER to get out of.

### CODE REVIEW

**Comment by danchoi** [comment]
Thanks. Do you want to release your build as a tiger-specific version of vitunes called `vitunes-10.5` or something? I would be happy to point to it from the webpage. I'm asking you if you want to be the maintainer of the 10.5 fork.

I think you might be able to suppress the tdta errors with some unix stream redirectors -- just a guess.

**Comment by dgilman** [comment]
Thanks for the lead on the stream redirection, that's fixed up the problem.  Sure, I can just keep a fork around.

**Comment by danchoi** [comment]
Cool that it worked! Can you release the gem of this fork to rubygems.org or do want me to? Either way is fine with me.

**Comment by dgilman** [comment]
I'm not familiar with rubygems at all so can I take this as a learning experience?  I'll take a stab at it over the weekend.  Is the vitunes-10.5 name suitable?

**Comment by danchoi** [comment]
Of course. vitunes-10.5 sounds great.

**Pull request closed without merging**
